### ISSUE TITLE
dir-locals issue

### ISSUE THREAD

**Issue by achikin** [day8/re-frame-template#114]
The template generates `.dir-locals.el` only when `+cider` key is provided.
`.dir-locals.el` only make sense for emacs, but emacs/cider loads all cider jars automatically on jack-in so you don't need to add them to project dependencies and therefore you don't need to pass `+cider` key if you intend to work with emacs.
On the other hand other editors like VSCode can benefit form cider middleware, but those editors does't need `.dir-locals.el`
Wouldn't it make more sense to generate `.dir-locals.el` nonetheless `+cider` is provided?

**Comment by michaelknowles** [comment]
Since, like you mentioned, only emacs benefits from `.dir-locals.el`, I don't think it should be generated by default.  Maybe there could be a `+emacs` flag?  Is there anything else emacs-specific that could be put in that?

**Comment by achikin** [comment]
IMO could be simply `+dir-locals` this could be really handy and won't disturb the other settings.

**Comment by PEZ** [comment]
I'm of the opinion that it makes sense to always create the editor settings for all the editors. Once more than one person works with the project chances are that another editor enters the scene.

That said, I don't think anyone needs the `.dir-locals.el` file any longer, CIDER probably just handles things smoothly. Saying that w/o knowing though, so I could be wrong.

**Comment by superstructor** [comment]
Closing based on last comment, and on inactivity for a long time. If this is still an issue for someone, please re-open the issue.
