### ISSUE TITLE
Encountering build error message "cljs.user is not available", but it disappears when I restart `lein dev`

### ISSUE THREAD

**Issue by humorless** [day8/re-frame-template#120]
When I modify the code, and then save. Everything is fine. 

However, if I modify the code, use vim fireplace to Evaluate the code, and then save, the following error shows up. 

```
[:app] Build failure:
The required namespace "cljs.user" is not available.
```

However, if I restart  `lein dev`, this error then disappears. 

Code is [here](https://github.com/humorless/sroi/tree/develop)

**Comment by stevejmp** [comment]
I also ran into this using [fireplace.vim](https://github.com/tpope/vim-fireplace).

A workaround is creating this namespace similarly to how Stuart Sierra describes in his [My Clojure Workflow, Reloaded article](http://thinkrelevance.com/blog/2013/06/04/clojure-workflow-reloaded) (scroll down to "Dev Profile and user.clj"):

1. In `project.clj`, add a new source path to the `:dev` profile:
    ```clj
    :profiles {:dev {:dependencies [ ... ]
                     :source-paths ["dev"]}
    ```
2. Create a directory for the namespace:
    ```sh
    mkdir dev/cljs
    ```
3. Create a source file for the namespace:
    ```sh
    vi dev/cljs/user.cljs
    ```
4. Add the namespace declaration, along with any dependencies you might find helpful in the REPL:

    ```clj
    (ns cljs.user
      (:require
        [cljs.repl :refer (Error->map apropos dir doc error->str ex-str ex-triage
                           find-doc print-doc pst source)]
        [clojure.pprint :refer (pprint)]
        [clojure.string :as string]))

    (comment
      (pprint (string/trim "Suppressing clj-kondo warnings")))
    ```

I think adding this to the base template or in an optional profile would be helpful to future users. @superstructor , what do you think?

**Comment by superstructor** [comment]
Sounds good @stevejmp :+1:
