### ISSUE TITLE
Template resource 'leiningen/new/re_frame/.clj-kondo/config.edn' not found

### ISSUE THREAD

**Issue by michaelknowles** [day8/re-frame-template#122]
`lein new re-frame testapp +garden +cider +kondo +test +routes +10x
Retrieving re-frame/lein-template/1.0.27/lein-template-1.0.27.pom from clojars
Retrieving re-frame/lein-template/1.0.27/lein-template-1.0.27.jar from clojars
Generating re-frame project.
Template resource 'leiningen/new/re_frame/.clj-kondo/config.edn' not found.`

`lein --version
Leiningen 2.9.1 on Java 13.0.1 OpenJDK 64-Bit Client VM`

Windows 10

**Comment by stevejmp** [comment]
Reproduced.

The published template JAR doesn't include the `.clj-kondo/` directory. The JAR produced by `lein uberjar` also doesn't include this directory.

I'm not sure if there's a build option to include hidden directories (starting with a `.`). I'll submit a PR with the directory renamed without the leading `.`, and @superstructor can decide what to do.

**Comment by JimLynchCodes** [comment]
Yes, I'm getting this error too when I try to scaffold with `+kondo`. 😥
