### ISSUE TITLE
The required namespace "create-react-class" is not available

### ISSUE THREAD

**Issue by michaelknowles** [day8/re-frame-template#123]
1. Installed template
2. lein deps
3. npm install
4. lein dev
`The required namespace "create-react-class" is not available, it was required by "day8/re_frame_10x/inlined_deps/reagent/v0v8v1/reagent/impl/component.cljs".
The namespace was provided via :foreign-libs which is not supported.`

Fixed by running:
`npm install create-react-class`

`create-react-class ^15.6.3` should be added to the template's package.json to prevent this issue in the future.

**Comment by superstructor** [comment]
Thanks for the report @michaelknowles :+1: However due to recent releases of reagent/react/re-frame no longer requiring create-react-class it is no longer an issue so closing.
