### ISSUE TITLE
Installation instructions for newbies

### ISSUE THREAD

**Issue by martimatix** [day8/re-frame-template#131]
It'd be nice to add some installation instructions for newbies. Maybe it's common knowledge among Clojurists that to install a lein script, you need to add it to `~/.m2` but for those that don't, some research is required.

**Comment by mike-thompson-day8** [comment]
@martimatix 
Could you give a more concrete example, please?  I'm not understanding what you mean by "installation instructions".   

Do you mean something like this: 
https://purelyfunctional.tv/guide/how-to-install-clojure/

**Comment by martimatix** [comment]
Suppose you're brand new to the world of Clojure and Clojurescript. You've read about the [new re-frame design](http://day8.github.io/re-frame/re-frame/) on reddit. You start reading about re-frame and you're sold. "I want to get started," you think to yourself. You go to the [Start Coding](http://day8.github.io/re-frame/start-coding/) page and see that there's a template to scaffold your project (this repo).

You're on a Mac and have run `brew install clojure` but don't really know much about Clojure or Leiningen.

You click on the link to this repo and start reading the [readme](https://github.com/day8/re-frame-template/blob/master/README.md). You read that you need to run `lein new re-frame <project-name>` but how do you _install_ it? That is to say, if I run `git clone https://github.com/day8/re-frame-template.git` in any old directory, Leiningen won't be able to find it.

For the sake of Clojurescript newbies, I was suggesting that something like this be added:

1. clone this repo
1. copy `src/leiningen/new` to `~/.m2/repository`
(by the way, is there an easier way?)

That was a long winded way of describing the situation that I found myself in. I ended up having to search for installing Leiningen templates and found [this page](http://jr0cket.co.uk/2015/03/clojure-templates-are-easy-with-leiningen.html).

Going through this experience prompted me to open this issue.

**Comment by martimatix** [comment]
Never mind, turns out that you don't need to clone this repo at all. 🤦‍♂️

`lein new re-frame <project-name>` is all you need.

**Comment by mike-thompson-day8** [comment]
I'm glad you worked it out.  

But you got me thinking, and I added this to the README <https://github.com/day8/re-frame-template/blob/master/README.md#before-you-start>.
