### ISSUE TITLE
Add lein-scss option

### ISSUE THREAD

**Issue by pcasaretto** [day8/re-frame-template#135]
Hi there,

Currently learning my way around re-frame and thought adding a [lein-scss](https://github.com/bluegray/lein-scss) option alongside lein-less would be a good idea.
If it is, I would be happy to take a stab at it.

**Comment by superstructor** [comment]
A PR for `+scss` is welcome :+1:

**Comment by superstructor** [comment]
Closing as we've moved from Leiningen to a pure shadow-cljs build setup, and as yet there is no third party scss shadow-cljs build hook available. If/when one is available we might be amenable to adding a `+scss+` option.
