### ISSUE TITLE
The upgrade of shadow-cljs to 2.10.17 breaks cider-jack-in-cljs

### ISSUE THREAD

**Issue by danielmartincraig** [day8/re-frame-template#137]
When I do M-x cider-jack-in-cljs, I'm prompted for a shadow-cljs build-
![Screenshot from 2020-07-23 21-01-23](https://user-images.githubusercontent.com/13541826/88354815-ccb42c80-cd27-11ea-8639-329d443411cb.png)

when I enter :app I get-
Unhandled clojure.lang.ExceptionInfo missing instance
![Screenshot from 2020-07-23 21-01-38](https://user-images.githubusercontent.com/13541826/88354841-e5244700-cd27-11ea-9bc9-d4d2b9d47771.png)

**Comment by danielmartincraig** [comment]
When I downgrade shadow-cljs to 2.10.15, this behavior disapears.

**Comment by kwrooijen** [comment]
I have this issue as well, even when I downgrade to `2.10.15`. When I create a `shadow-cljs.edn` file with the `:shadow-cljs` info from the generated `project.clj` file the issue is fixed. I'm not familiar with `lein-shadow` but I wonder how `cider` is supposed to parse this?

**Comment by danielmartincraig** [comment]
If you want to resolve this, just simply run lein watch at the command line before attempting to jack into this project

**Comment by danielappelt** [comment]
I think this can be closed. Running either `lein watch` or `lein deps` before jacking into the project with cider should fix the problem. Maybe it would be a good idea to add some upgrade instructions to the README.

**Comment by mike-thompson-day8** [comment]
I'd be happy to take a PR which added the right words to the README.  I'm not a cider user, so it is best I don't write them.

**Comment by zachmandeville** [comment]
Hi!  I am encountering this issue as well, even after running `lein watch` first.  I am uncertain if it's an issue with the template, the readme, or my editor.  Could this possibly be re-opened @danielmartincraig ?

Details for my error:
- I am running doom emacs and just upgraded to latest version as of 2020/12/15
- ran `lein new re-frame my-app +cider +10x +handler +kondo`
- in my-app repo ran  `lein deps` then `lein watch`
- opened repo in doom and in `src/cljs/my_app/core.clj` ran `cider-jack-in-cljs` 
- it gave me two options for running it: lein and shadow
- if i choose lein, I get this error about missing instance
- if I choose shadow, i get `server already running`, but remain disconnected from repl
` if i run `cider-connect-cljs` and choose `localhost:8777` (which lein watch logs as being the nrepl port) I get a repl in emacs, and I can evaluate commands in the repl (e.g. running `(js/alert "hi")` shows an alert box on localhost:8280 with the message "hi")
- however, I cannot evaluate code in the buffer, or send expressions from my buffer to the repl, as i get the error 'not connected to any repl sessions'

This is my first re-frame project, and I was assuming I'd be able to evaluate commands in the buffer and do var lookups and such in the same way as a clojure project.  is that an incorrect assumption?

**Comment by danielmartincraig** [comment]
So here's what I think will work - after running lein watch, then kill the lein watch.  After that, then do cider-jack-in-cljs, and select shadow-cljs.  proceed from there, this is what works for me.  I think that jacking in while lein watch continues to run causes your cider to not do the c-x c-e evaluations like you are looking for and stuff.

**Comment by zachmandeville** [comment]
Yep, that worked!  Jacking in with shadow-cljs seemed to be the key.  Thank you, @danielmartincraig !
