### ISSUE TITLE
Use lein doo for testing

### ISSUE THREAD

**Issue by danielcompton** [Day8/re-frame-template#14]
[doo](https://github.com/bensu/doo) is a good test runner for ClojureScript testing. It would be good to add this to the re-frame template to get others set up with it easily.

**Comment by gadfly361** [comment]
Sounds good! Do you think this should be put in the current `+test` option, or be its own?

**Comment by danielcompton** [comment]
I feel like it could almost replace the current `+test` option, though because it is a mildly opinionated testing framework, it might be good to have it as a separate option to the more vanilla phantom testing that exists currently. There's a doo release [pending](https://github.com/bensu/doo/issues/63), I'll take a look at this more closely once the release goes out.

**Comment by gadfly361** [comment]
Updated the `test` profile to use [doo](https://github.com/bensu/doo), and kept the minimal example showing use of phantomjs.

**Comment by gadfly361** [comment]
Closing this (please re-open if I missed the mark though)
