### ISSUE TITLE
server.clj errors when port is given from environment

### ISSUE THREAD

**Issue by maxov** [day8/re-frame-template#140]
When the port is given to server.clj from the environment, e.g. as an environment variable or from a config file:
```PORT=3001 lein run -m my-app.server```

The following error results:

```
Syntax error (ClassCastException) compiling at (/private/var/folders/b0/m9d16cp90mg44bxkmd5mh_x80000gn/T/form-init14644285568750398614.clj:1:126).
class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')
```

This happens because:
1. server.clj [delegates to yogthos/config](https://github.com/day8/re-frame-template/blob/master/src/leiningen/new/re_frame/src/clj/server.clj#L8) for finding the port first
2. yogthos/config [converts to port string to a long](https://github.com/yogthos/config/blob/master/src/config/core.clj#L36-L44)
3. The signature of `Integer/parseInt` takes a String, forcing a class cast from the port, and causing the error

Recommended fix:
- Just remove `Integer/parseInt` as in [reagent-template](https://github.com/reagent-project/reagent-template/blob/master/resources/leiningen/new/reagent/src/clj/reagent/server.clj#L9), because config will ensure it is a number

It's also possible to replace with a call to `Integer.` as [ring-server](https://github.com/weavejester/ring-server/blob/master/src/ring/server/options.clj#L13) does, but I think the reagent-template has it best here (the config library already ensures it's a number, any further casting is spurious). I'm happy to create a PR with the fix if needed.

**Comment by superstructor** [comment]
Thanks @maxov 👍  Good find and fix. Will release momentarily.
