### ISSUE TITLE
REPL Jack-in is not working at the Calva under WSL2

### ISSUE THREAD

**Issue by mikebohdan** [day8/re-frame-template#141]
I try to run a freshly created project and it stuck at "Jacking In phase".
The project is started though

```
shadow-cljs - HTTP server available at http://localhost:8280
shadow-cljs - HTTP server available at http://localhost:8290
shadow-cljs - server version: 2.11.0 running at http://localhost:9630
shadow-cljs - nREPL server started on port 8777
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (206 files, 205 compiled, 0 warnings, 61.52s)
```

The project was created by a `lein new re-frame app +less +calva +kondo +test`

My setup is:
VSCode version 1.46.1
Calva version 2.0.124
Windows 2004
JDK 11
Node 12.18.3
Firefox 80.0.1

PS: same projects perfectly works on a Mac machine but on Windows

**Comment by danielmartincraig** [comment]
try running `lein watch` at the command line before attempting to jack in

**Comment by mikebohdan** [comment]
But the same project jacking in just fine on macOS without `lein watch` or other command-line manipulations.

**Comment by danielmartincraig** [comment]
What was the result of running lein watch?

**Comment by mikebohdan** [comment]
I found that it is due to this one https://github.com/microsoft/WSL/issues/5439.
