### ISSUE TITLE
Add cider/cider-nrepl plugin

### ISSUE THREAD

**Issue by MrSFGriffin** [day8/re-frame-template#148]
Hello,

I found things worked better with cider when I added `[cider/cider-nrepl "0.25.6"] `to the plugins in project.clj.

Perhaps, adding `{{#cider?}}[cider/cider-nrepl "0.25.6"]{{cider?}}` to the project.clj template file would improve things for others.

**Comment by superstructor** [comment]
As I am not currently a cider user it would be helpful to get a PR from someone who is so they can also test it.

**Comment by MrSFGriffin** [comment]
PR: https://github.com/day8/re-frame-template/pull/149.

**Comment by superstructor** [comment]
Merged #149
