### ISSUE TITLE
Sente option?

### ISSUE THREAD

**Issue by metasoarous** [Day8/re-frame-template#15]
Feel like sente fits into this picture like a glove on a hand. Would be nice to have that as an option.

**Comment by danielcompton** [comment]
Not sure how I feel about this. Sente integration is going to be a little bit custom for each application. It's also another dependency which needs to be kept up to date. Open to others ideas though.

**Comment by gadfly361** [comment]
I've never used Sente (not really sure what would be involved in terms of integration), so I default to @danielcompton. 

@mike-thompson-day8 do you have any thoughts on this?

**Comment by mike-thompson-day8** [comment]
I feel as if Sente is out of scope for this template.  it would be good to have explanations for how to introduce it somewhere, but we have to say no to anything that complicates the basics.

**Comment by gadfly361** [comment]
Seems like this particular option is out of scope. However, really appreciate issues like this to see what options we want to include :)

**Comment by metasoarous** [comment]
This being closed, I apologize for not commenting sooner, but here are a few of my thoughts on this:

* re-frame is all about "stream everywhere", yes? To me that makes something like Sente a very appealing direction for client/server communication.
* While using Sente use ends up being pretty custom for each application, I think the most basic templating of things to get the data flowing might not be so bad.

That having all been said, if it still seems out of scope to you, I'd agree that some documentation on how to merge Sente (or Chord) and re-frame would be really valuable. Or perhaps someone will create a separate template with this particular configuration.
