### ISSUE TITLE
println doesn't work out of the box

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame-template#16]
The other day I had to quickly run up a test,  and I turned to this template ... but my `println`s didn't work.  
Easily fixed, of course, just add this to `core.cljs`: 
```
(enable-console-print!)
```

But I wondered, for the sake of cljs newbies, should we make that happen by default??  

Happy to be shouted down, but wondered.

**Comment by danielcompton** [comment]
It's in plenty of other quickstart guides and templates so I don't see why not.

**Comment by gadfly361** [comment]
Trying to add `(enable-console-print!)` for the _dev_ build and not the _min_ build.

To avoid using the [env folder method](https://github.com/plexus/chestnut/tree/master/src/leiningen/new/chestnut/env) taken by chestnut template, I'm attempting to use the [`goog-define` method](http://www.martinklepsch.org/posts/parameterizing-clojurescript-builds.html).  When I build using `lein cljsbuild once dev` and `lein cljsbuild once min`, everything works as expected (i.e., logs showing in the console for the dev build and no logs for the min build). However, when I use `lein figwheel dev` the build is unsuccessful.

@danielcompton I see that you noted experiencing this same thing in this lein-figwheel [issue](https://github.com/bhauman/lein-figwheel/issues/262).  Bruce mentioned this was fixed as of v0.5.0; however, when I bumped the figwheel version, I was still experiencing this build error ... do you have any insight?  I am working on branch _16/println_

**Comment by gadfly361** [comment]
I apologize for noise. I think the above was a user error :)

I bumped to lein-figwheel 0.5.0-2 (with this [commit](https://github.com/Day8/re-frame-template/commit/c1ccfd90bc592479a1f539c3f603cea838f19861)) and everything works fine.  Let me know if there are any reservations about using `goog-define` ... I've never used it before, but seems like this is a good use case.

**Comment by danielcompton** [comment]
It would probably be more common to use `goog.DEBUG` as the check instead of making our own goog define in this case, as their purposes seem to overlap a lot.

**Comment by mike-thompson-day8** [comment]
I'm not sure about this BUT,  you might need to do:
```
(when ^boolean dev?
    (enable-console-print!))
```

Certainly you need a hint if you do this:
```
(when  ^boolean js/goog.DEBUG
    (enable-console-print!))
```

**Comment by gadfly361** [comment]
@danielcompton, I updated the code to use `goog.DEBUG`. @mike-thompson-day8, I included a `^boolean` hint when using `goog.DEBUG`.

**Comment by mike-thompson-day8** [comment]
Looks good!

**Comment by gadfly361** [comment]
Awesome! Merged branch and pushed to clojars.  Also bumped re-com and garden versions.
