### ISSUE TITLE
Make a fallback to index.html correctly

### ISSUE THREAD

**Issue by mattdamon108** [day8/re-frame-template#161]
I'm building a SPA with re-frame on shadow-cljs. I encountered an issue to make a fallback to index.html. It's working fine with single path without slash. (eg. `http://localhost:8280/profile`) It is successfully fallen back to index.html in `resources/public`.

```clojure
:dev-http     {8280 "resources/public"
                8290 "target/browser-test"}

 :builds       {:app {:target     :browser
                      :output-dir "resources/public/js/compiled"
                      :asset-path "/js/compiled"
                      ... }
```

But if I add a dangling slash in url (eg. `http://localhost:8280/profile/`) or try to reach to sub paths (eg. `http://localhost:8280/oauth/google/redirect`) It fails to find the index.html in `resources/public`, instead it returns 404 error which seems looking for the asset in relative path (eg. `/profile/js/compiled`, `/oauth/google/js/compiled`)

I found the simple solution to fix this issue with adding an slash to path of js in `index.html` which is auto generated in `resources/public`.

```html
# from
<script src="js/compiled/app.js"></script>

# to
<script src="/js/compiled/app.js"></script>
```

Probably, it could make an unexpected behaviour in case of using proxy configuration or else. But I think it is more suitable for the most basic configuration of SPA.

**Comment by superstructor** [comment]
Fixed in #162
