### ISSUE TITLE
Hot reloading can break navigation with +routes option

### ISSUE THREAD

**Issue by Sose** [day8/re-frame-template#163]
Currently navigation handled by Bidi/Pushy (+routes option) gets broken whenever certain files get hot reloaded.

Steps to reproduce
- Make a new project with `lein new re-frame brokennav +10x +cider +routes`
- cd inside, `npm install`, `npm run watch`
- wait...
- open localhost:8280
- click on the links, they work
- open `src/brokennav/events.cljs`
- add an empty line with a comment ";"
- save the file, browser hot reloads your code
- the links don't work anymore

**Comment by Sose** [comment]
I submitted a pull request that should fix this, but I was unable to link it inside GitHub

https://github.com/day8/re-frame-template/pull/164

**Comment by superstructor** [comment]
Fixed in #164
