### ISSUE TITLE
Browser console error - "The message port was closed before a response was received"

### ISSUE THREAD

**Issue by nickdex** [day8/re-frame-template#167]
After following the steps for creating the project and running from emacs (cider-jack-in-cljs) and opening http:localhost:8280,  you can see this console error.

![image](https://user-images.githubusercontent.com/8512967/134834161-c0cdf6f8-9438-4066-93ea-0ed198aba84b.png)

OS: Windows 10

**Comment by superstructor** [comment]
@MawiraIke Can you see if you can reproduce this error when jacking in from emacs ?

**Comment by MawiraIke** [comment]
Okay, on it @superstructor .

**Comment by kimo-k** [comment]
Can't repro, though I am on linux, not Windows. Feel free to reopen if this is still happening. My best guess is that upgrades to cider, nrepl, etc... may have solved this already, or it could be caused by something in your system config, such as an antivirus/firewall.
