### ISSUE TITLE
Template resource 'leiningen/new/re_frame/.github/workflows/test.yaml' not found.

### ISSUE THREAD

**Issue by danielcompton** [day8/re-frame-template#168]
I tried to create a new re-frame template app but got an error when I tried to add `+github-actions`.

```console
$ lein new re-frame test-template +github-actions 
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
Generating re-frame project.
Template resource 'leiningen/new/re_frame/.github/workflows/test.yaml' not found.
```

I don't really understand the error as the file seems to exist: https://github.com/day8/re-frame-template/blob/master/src/leiningen/new/re_frame/.github/workflows/test.yaml.

**Comment by superstructor** [comment]
Thanks for taking the initiative to fix this @sevillaarvin as had missed the simplicity of it being a `.` where there should have been none.
