### ISSUE TITLE
re-frame template based apps with docker?

### ISSUE THREAD

**Issue by luposlip** [Day8/re-frame-template#20]
I need an example/template/option that helps/hints/generates needed files to make re-frame-template generated app run inside a docker container.

I'm currently running figwheel in a container, but
1: cannot communicate with it from my host mac (port mapping?), and
2: of course I shouldn’t use figwheel in production but cljsbuild once, and
3: I should probably use uberjar, but cannot find a project.clj that has both nice figwheel for re-frame and profiles for uberjar (and never understood leiningen project.cjl deeply enough to know exactly what to do myself)

Thanks! :)

**Comment by gadfly361** [comment]
Here is a possible way to create a basic docker container that serves up static files. (FYI: I am a docker noob, so take this with a grain of salt.)

**Step 1: Create a re-frame application from the template**

```
$ lein new re-frame docker-example
```

**Step 2: Create a `Dockerfile` that can serve up your static files (going to use [nginx](https://hub.docker.com/_/nginx/))**

```
FROM nginx:1.9.9

COPY ./resources/public /usr/share/nginx/html
```

**Step 3: Create your minified js files**

```
$ lein clean
$ lein cljsbuild once min
```

**Step 4: Build your docker image**

```
docker build -t re-frame-image .
```

Note: If this was successful, you should see something similar to the following when you run `docker images`

```
REPOSITORY                  TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
re-frame-image              latest              628198000d32        7 seconds ago       134.2 MB
```

**Step 5: Create and run a container based on that image**

```
docker run --name re-frame-container -d -p 8080:80 re-frame-image
```

If you navigate to http://localhost:8080/  you should see your application.

Note: Your container is running. If you type `docker ps`, you should see something like the following:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                           NAMES
d0982f1b8813        re-frame-image      "nginx -g 'daemon off"   About a minute ago   Up About a minute   443/tcp, 0.0.0.0:8080->80/tcp   re-frame-container
```

If you want to stop the container, run `docker kill re-frame-container`

**Comment by luposlip** [comment]
Thanks a lot, appreciate it.
This would be great to have in the documentation! :+1:

**Comment by pepe** [comment]
It works as advertised. 

:+1: for the documentating this.
