### ISSUE TITLE
Idea: Scaffolding for re-frame generators

### ISSUE THREAD

**Issue by kristianmandrup** [Day8/re-frame-template#21]
Just some ideas for how to build large projects built on domain models and standardised patterns/vocabulary, structure etc. WIP

Create todo domain model with basic scaffolding: 

`re-frame new todo`

File structure

```
+ todo
  todo-views.cljs
  todo-handlers.cljs
  todo-subscribers.cljs
  todo-utils.cljs
```

Scaffolding using conventions

```cljs
(ns todo.views
    (:require [re-frame.core :refer [subscribe dispatch]]))

;; todo-views

(defn todo-actions [id]
  [:div {:class "actions"}
    [:button "Update" #(dispatch [:update-todo item])]
    [:button "Delete" #(dispatch [:del-todo item])]
  ]

(defn todo-item [item]
  [let item (subscribe [:get-todo-item item])
    [:li (:name item)] (todo-actions item)])

(defn todo-list []
  [let list (subscribe [:get-todo-list])
    [:div
      [:ul
        (for [item list]
          (todo-item item))
      ]
      [:button "Create new Todo" #(dispatch [:new-todo])]
    ]
   ])
```

```cljs
(ns todo.handlers
    (:require [re-frame.core :refer [register-handler]]))

;; todo handlers

(defn new-todo []
  (fn [db, [id]]
    ;; ...
    ))

(defn edit-todo []
  (fn [db, [id]]
    ;; ...
    ))

(defn del-todo []
  (fn [db, [id]]
    ;; ...
    ))

(register-handler :new-todo new-todo)
(register-handler :edit-todo edit-todo)
(register-handler :del-todo del-todo)

```cljs
(ns todo.subscribers
    (:require-macros [reagent.ratom :refer [reaction]])

;; todo subscribers
;; use reactions

return single item record
(defn get-todo-item [db, [id]] {id: 1 name: "Todo item"})

;; return list of item ids
(defn get-todo-list [db, []] [1])
```

These scaffolding templates could (naturally) be customised on a per project or technology stack level

**Comment by danielcompton** [comment]
I've been thinking about this a little bit too, https://github.com/weavejester/lein-generate, or https://github.com/seancorfield/boot-new/issues/3 would both be good for this. Or you could use something like yeoman?

**Comment by kristianmandrup** [comment]
I have good experience with Slush for this ;)

http://slushjs.github.io/#/

**Comment by kristianmandrup** [comment]
Started something here... https://github.com/kristianmandrup/slush-reframe

**Comment by gadfly361** [comment]
@kristianmandrup Oh this is a fun idea! I've never used slush before, but interested to try out slush-reframe. Since it isn't on npm yet, how would I go about using it locally?

**Comment by kristianmandrup** [comment]
I made some fixes, tested it out in a real project. Looks to be working now, just need better templates ;) 

Also updated README with instructions for running locally and developing/debugging to fit your own needs...

**Comment by kristianmandrup** [comment]
I published `slush-reframe` version 0.1.0 after testing it in Cursive IDE. Looks fine now.

**Comment by gadfly361** [comment]
Sweet, just made my first scaffold with slush-reframe. Thanks for creating this!  If you'd like to add a link in re-frame-template README to your repo, I'd be happy to accept the PR. Probably a short blurb at the bottom of the usage section.

As an aside, looks like the subscribes are missing an inner (fn [] ... ) between them and the hiccup.

**Comment by kristianmandrup** [comment]
Thanks :)

**Comment by gadfly361** [comment]
Added link. Oh awesome, keep me posted about the book :+1:
