### ISSUE TITLE
shouldn't be anything in core.clj?

### ISSUE THREAD

**Issue by sihingkk** [Day8/re-frame-template#23]
the file is empty

**Comment by gadfly361** [comment]
@sihingkk Yeah, I  can see how that would seem like a mistake: however, the empty file is intentional. My thought there is to strongly encourage placing clojurescript files at `src/cljs` and clojure files at `src/clj`. The empty file is intended to be a hint to that file structure.

**Comment by sihingkk** [comment]
I understand that, shoudnt be there something starting server, when you choose +handler?

Or server is started in different way?

**Comment by gadfly361** [comment]
Ahh, yes. If you choose the `+handler` option, there will be something in a new file called `handler.clj` and `core.clj` is still there, just empty.

**Comment by gadfly361** [comment]
Closing this; however, feel free to reopen to continue the discussion.
