### ISSUE TITLE
Watch Clojure (backend) files for changes and reload?

### ISSUE THREAD

**Issue by fasiha** [Day8/re-frame-template#24]
Sorry, this isn't necessarily a re-frame-specific issue but reflects my ignorance of the broader lein workflows. I understand that figwheel shouldn't be held responsible for reloading my Clojure `.clj` files if they change, since that handles the front-end. However, is there a recommended way to watch for changes in `/src/clj` and reload them? Specifically, as I add endpoints to `handler.clj` (made with `+handler`), I'm finding that `lein figwheel dev` won't see them until I restart lein.

**Comment by gadfly361** [comment]
@fasiha Take a look at [this section](https://github.com/bhauman/lein-figwheel#figwheel-server-side-configuration) of the figwheel docs.  In there you will see something like this:

```
   :ring-handler example.server/handler

   ;; Clojure Macro reloading
   ;; disable clj file reloading
   ; :reload-clj-files false
   ;; or specify which suffixes will cause the reloading
   ; :reload-clj-files {:clj true :cljc false}
```

I haven't tried this, but adding `:reload-clj-files true` to the figwheel portion in your project.clj may do the trick.  Given how the comment is written though, it sounds like the default is to reload the clj files.

**Comment by fasiha** [comment]
@gadfly361 thanks for pointing this out. The [figwheel wiki](https://github.com/bhauman/lein-figwheel/wiki/Configuration-Options#server) does specify that `:reload-clj-files` defaults to off, but setting it to true in my `project.clj` (in the top-level `:figwheel` map, not the one under `cljsbuild`!) doesn't seem to work, and a hint to why may be provided in that wiki:
> Clojure Macro reloading
Even though compojure's `defroutes` is a macro, perhaps figwheel means something very specific when it says "macro reloading"? I'll look into this more.

**Comment by not-much-io** [comment]
If you want cljs + clj reloading you can do that with wrap-reload, have a look at this small apps handler: https://github.com/not-much-io/remind-me/blob/master/src/clj/remind_me/handler.clj 

This is where the middleware is explained: https://github.com/ring-clojure/ring/wiki/Reloading

**Comment by fasiha** [comment]
@not-much-io thank you 🍻! In short, just change `clj/.../handler.clj` that's produced by the template to import the `wrap-reload` ring middleware, and wrap it around your actual handler. So, with minimal changes to the original:

```clj
(ns reframe-compojure.handler
  (:require [compojure.core :refer [GET defroutes]]
            [ring.util.response :refer [file-response]]
            [ring.middleware.reload :refer [wrap-reload]])) ;;; (1) import

(defroutes routes ;;; (2) rename
  (GET "/" [] (file-response "index.html" {:root "resources/public"})))
(def handler (-> #'routes wrap-reload)) ;;; (3) define and wrap
```
I'll put together a PR with this, and another change that binds `compojure.route/resources` to `/` so that the JS assets are loaded as well as `index.html`.

**Comment by gadfly361** [comment]
PR would be great!

**Comment by fasiha** [comment]
Another (semi-related?) aspect of this is, if your Ring handler has compilation errors, neither `rlwrap lein figwheel dev` nor `lein repl` will tell you. If you have the `lein-ring` plugin, and do something like `lein ring headless-server`, then you get the stacktrace. I'm not sure why this happens or how to address this.

**Comment by fasiha** [comment]
@gadfly361 & re-frame-template maintainers, here's where I'm stuck. I could put together a very simple PR that uses Ring's `wrap-reload` middleware, but like I said, errors in Clojure-land are hard to detect when figwheel's webserver (http-kit) is loading our Compojure routes.

On the other hand, re-frame-template could include a separate webserver—as recommended by figwheel's documentation 😋. The way I do that personally is, an http-kit server is started from a `(-main)` in `src/app/handler.clj` with `$ lein run`. Then, in another terminal, I run `lein figwheel…` to start figwheel, on its own port, but I can use my site without figwheel running (I'll just get regular `console.error`s saying "zomg figwheel websocket to server not established). I can try to understand this workflow better and polish it up to best-practices (I already can generate uberjars! and they work!!!) and can build a PR around this approach, but only if you think that's an acceptable way for the `+handler` profile to work?

**Comment by gadfly361** [comment]
@fasiha I'm happy for the `+handler` to evolve to fit the community's needs!  A PR with the second workflow would be welcomed :)

**Comment by fasiha** [comment]
Thanks for the feedback! Question—you think users will be mad that they need to run two commands (`lein run` & `lein figwheel dev`) in two terminals to get the good experience?

**Comment by gadfly361** [comment]
@fasiha I think running both commands is a small burden for the better experience, so I say go for it!
