### ISSUE TITLE
lein-figwheel 0.5.3 fails to start

### ISSUE THREAD

**Issue by andrerichards** [Day8/re-frame-template#29]
`re-frame-template` currently configures a new project with `lein-figwheel` `0.5.3` but there seems to be a problem with that version.

Replacing the version of `lein-figwheel` in the generated project with the latest version (`0.5.4-3`) fixes the problem. 

Please consider updating re-frame-template to the latest version of lein-figwheel.

### Steps to recreate
Follow usual steps to create a new project:
`lein new re-frame <project-name> `

Change to project folder, then:
`lein clean`
`lein figwheel dev`

This fails with exception:
`clojure.lang.Compiler$CompilerException: java.io.FileNotFoundException: Could not locate fipp/visit__init.class or fipp/visit.clj on classpath., compiling:(figwheel_sidecar/config_check/type_check.clj:1:1)`
[stacktrace.txt](https://github.com/Day8/re-frame-template/files/315617/stacktrace.txt)

### Workaround
Open `project.clj` and replace `[lein-figwheel "0.5.3"]` with `[lein-figwheel "0.5.4-3"]`

Do
`lein clean`
`lein figwheel dev`

**Comment by gadfly361** [comment]
Thanks for the heads up, just bumped figwheel to latest.
