### ISSUE TITLE
compatibility with elixir phoenix

### ISSUE THREAD

**Issue by igoodrich** [Day8/re-frame-template#31]
Hi! Thank you for re-frame.
This is not so much an issue as an offer to help.

I think it would be pretty easy to make a version of this lein template that was compatible with http://www.phoenixframework.org/

Basically, there's no need for:
resources/public/index.html
and the clj/cljs directories need to be rooted in web/static
and the build output dir is priv/static/js/cljs

Like this:

```clojure
(defproject my-example "0.1.0-SNAPSHOT"
  clj.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.8.51"]
                 [reagent "0.5.1"]
                 [binaryage/devtools "0.6.1"]
                 [re-frame "0.7.0"]]

  :plugins [[lein-cljsbuild "1.1.3"]]

  :min-lein-version "2.5.3"

  :source-paths ["web/static/clj"]

  :clean-targets ^{:protect false} ["priv/static/js/cljs" "priv/static/js/cljs-adv" "target"]

  :figwheel {:css-dirs ["priv/static/css"]}

  :profiles
  {:dev
   {:dependencies []

    :plugins      [[lein-figwheel "0.5.4-3"]]
    }}

  :cljsbuild
  {:builds
   [{:id           "dev"
     :source-paths ["web/static/cljs"]
     :figwheel     {:on-jsload "my-example.core/mount-root"}
     :compiler     {:main                 my-example.core
                    :output-to            "priv/static/js/cljs/app.js"
                    :output-dir           "priv/static/js/cljs"
                    :asset-path           "js/cljs"
                    :source-map-timestamp true}}

    {:id           "min"
     :source-paths ["web/static/cljs"]
     :compiler     {:main            my-example.core
                    :output-to       "priv/static/js/cljs/app.js"
                    :optimizations   :advanced
                    :closure-defines {goog.DEBUG false}
                    :pretty-print    false}}

    ]}

  )
```

I could make a version of this template that did all that (and presumably there would be a way to share it), but I'm not precisely sure how _best_ to do it.  This template has all of re-frame in, near as I can tell... Not sure what to do about that...  And then even if it were duplicated (assuming that were remotely kosher), how to reliably keep it up to date.

Once these changes are done and the generated code is moved to the correct directory, everything is grand.  When you run `lein figwheel dev` while the phoenix server is running it all connects and you get a live repl even without any of the stuff in the resources directory.  Swell!

Anyway, with a little guidance, I'm happy to put something together that others can use and that has a good out of box with phoenix.  People are excited about phoenix and for good reason.  Some people are using Elm, but I'm not one of them currently :).  I think supporting re-frame/clojurescript on phoenix could potentially be a popular and sensible option.  It'd be great if people could try it without the fussing around.

Thanks, again.

**Comment by gadfly361** [comment]
@igoodrich Thanks for your post! I have given this some thought, and I think adding elixir / phoenix support is outside the scope of this template. However, if you wanted to make a fork or create a similar template that includes it, you have our blessing! Also, I am absolutely willing to help if you decide to do that.  I can be found on clojurians slack with the handle @gadfly361 if you want to bounce some ideas around :)

**Comment by igoodrich** [comment]
Excellent!  Thanks -- yes, I'll just make a separate template based on this.  I should not be hard to do, but I did want to get your thoughts first.  I may reach out on slack once I get going and may ask you to review what I did if it seems at all hairy.  Thanks again!

**Comment by gadfly361** [comment]
Sweet, sounds good!

**Comment by dfcarpenter** [comment]
@igoodrich I have created a new phoenix project,added the reframe template, and updated my project.clj. I tried updating the layout.html.eex with  js/cljs/app.js (in addition to the js/app.js already present and this doesn't seem to work. Any ideas?

**Comment by igoodrich** [comment]
HI @dfcarpenter -- Sorry I just saw this. Still having issues?  If so, I can try to do what I said at least in draft form this weekend...

**Comment by igoodrich** [comment]
@dfcarpenter It really does work well once it's all set up.
