### ISSUE TITLE
debug? not defined correctly

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame-template#44]
I'm not sure we have the following code right for achieving Dead Code Elimination (DCE):
https://github.com/Day8/re-frame-template/blob/master/src/leiningen/new/re_frame/src/cljs/config.cljs#L3

It currently reads:
```
(def debug?
  ^boolean js/goog.DEBUG)
```

But I think it should instead be:
```
(def debug?
   "@const {boolean}"      ;;   <---- tells Closure compiler the value doesn't change
  ^boolean goog.DEBUG)     ;;   <---- removed js/  ... David Nolen says not to
```

But both my assertion of DCE failure and the proposed fix are untested.  I'm just quickly dropping this in here so I don't forget.

**Comment by mike-thompson-day8** [comment]
https://dev.clojure.org/jira/browse/CLJS-2023

**Comment by mike-thompson-day8** [comment]
After further experiments, i can now confirm that we can simply swap to:
```
(def ^boolean debug? 
   ^boolean goog.DEBUG)
```

**Comment by gadfly361** [comment]
@mike-thompson-day8 I don't think I see a change in the resulting js file size.

If I create a project like this:
```
lein new re-frame mytest
```

And then run:
```
lein clean
lein cljsbuild once min
```
On the following variants, and I get the same js file size.

---

```
(def debug?
   ^boolean js/goog.DEBUG)
```
336503

```
(def debug?
   ^boolean goog.DEBUG)
```

336503

```
(def debug?
  "@const {boolean}"
  ^boolean goog.DEBUG)
```

336503

```
(def debug?
  "@const {boolean}"
  ^boolean js/goog.DEBUG)
```

336503

**Comment by gadfly361** [comment]
Doh, nevermind - I can reproduce. I forgot to upgrade the clojurescript version.

---

```clojure
(def debug?
   ^boolean js/goog.DEBUG)
```

336348

```clojure
(def debug?
   ^boolean goog.DEBUG)
```

335267

```clojure
(def debug?
  "@const {boolean}"
  ^boolean goog.DEBUG)
```

335267

```clojure
(def debug?
  "@const {boolean}"
  ^boolean js/goog.DEBUG)
```

336348

**Comment by mike-thompson-day8** [comment]
> I can reproduce. I forgot to upgrade the clojurescript version

Yep. For record, the problem exists in ClojureScript version 1.9.456 onwards.

**Comment by gadfly361** [comment]
For anyone interested, here is a great post by @martinklepsch related to this issue:
https://www.martinklepsch.org/posts/requiring-closure-namespaces.html
