### ISSUE TITLE
Use .dir-locals?

### ISSUE THREAD

**Issue by wiseman** [Day8/re-frame-template#49]
The README says

> Put this in your Emacs config file:
>
>```
>(setq cider-cljs-lein-repl "(do (use 'figwheel-sidecar.repl-api) (start-figwheel!) (cljs-repl))")
>```

Instead of making users manually set `cider-cljs-lein-repl` and manage conflicts between projects that require different values for that variable, what do you think about adding a `.dir-locals.el` file, like the [chestnut template does](https://github.com/plexus/chestnut/blob/master/src/leiningen/new/chestnut/.dir-locals.el)?

Besides avoiding conflicts, it would also mean one less manual step is required before being able to use the generated project.

**Comment by gadfly361** [comment]
@wiseman Oh cool, I have never used something like that before. I would be happy to review a PR if you are interested :)

**Comment by superstructor** [comment]
This is now on master as per [shadow-cljs docs](https://shadow-cljs.github.io/docs/UsersGuide.html#cider).
