### ISSUE TITLE
Use namespaced keywords for events, subscriptions, db (, routes, ...) for greater readability

### ISSUE THREAD

**Issue by orolle** [Day8/re-frame-template#58]
Hi,
I am new to re-frame and I was playing around to learn the technology. I was confused because of the similar looking non-namespaced keywords and the resulting errors. I decided to namespace all of them and found out that the namespaced keywords perfectly match the dominos and makes it perfectly clear where to use which keyword. Also it makes modularization of the app very natural. 

For example :set-active-panel will result in :my-app.events/set-active-panel (or ::events/set-active-panel).

Sounds totally trivial but this helped me a lot. Maybe also interesting for the todo example.

**Comment by gadfly361** [comment]
@orolle Thanks for opening this issue, and I agree! I also enjoy using namespaced keywords and think the template should be updated to reflect that. This would be an easy PR if anyone wants to pick it up :) Otherwise I'll be able to get to it in a few days (currently in transit).

**Comment by gadfly361** [comment]
Template now uses namespaced keywords

**Comment by panewman** [comment]
Are you sure you did that right? I got (re-frame/subscribe [::subs/name]) in the views and I would rather expect just one ':' (the compiler also complains).

**Comment by gadfly361** [comment]
@panewman yeah, pretty sure. 

The documentation can be found here (see last bullet underneath keywords):
https://clojure.org/reference/reader#_literals

And for a more digestible reference (see the end of the post):
https://kotka.de/blog/2010/05/Did_you_know_III.html

If the compiler is complaining, it is likely you are trying to reference a subscription that isn't defined in the subs namespace yet.

**Comment by panewman** [comment]
I probably missed some compiler error in the subs namespace, that prevented the definition of subs/name.
Thank you very much.
