### ISSUE TITLE
Race Condition in App Bootstrap

### ISSUE THREAD

**Issue by mike-thompson-day8** [Day8/re-frame-template#62]
I believe there's a race condition in the way the application bootstrap is written:
https://github.com/Day8/re-frame-template/blob/master/src/leiningen/new/re_frame/resources/public/index.html#L15-L16 

`app.js` must be fully loaded before `init()` can be called.  If it isn't, then there'll be an Reference Error (because the necessary `js` just isn't loaded yet).  And yet the current code doesn't guarantee this fully-loaded-before-call requirement.  

The solution is easy - change the script part to be:
```
<script>
   window.onload = function () { 
       {{sanitized}}.core.init(); 
   }
</script>
```
Now `init()` doesn't happen before `app.js` is fully loaded. 

So ... 

I'm completely shocked that this hasn't come up before now.  How has this not failed all the time before now?  I'm Baffled.  I must be missing something - which accounts for me not doing a PR.  (Was just reported as a problem in Clojurians)

**Comment by thheller** [comment]
Saw this in Clojurians.

There is no race condition.

`<script>` without async will ensure that the `.js` is loaded completely before subsequent `<script>` tags run.

**Comment by mike-thompson-day8** [comment]
Thanks @thheller.  You've both educated me and put me out of my misery.  I was baffled.

**Comment by gadfly361** [comment]
@thheller +1 Thanks! I didn't know that either :)
