### ISSUE TITLE
with aliases lein dev stuck at garden auto "Successful"

### ISSUE THREAD

**Issue by yqrashawn** [Day8/re-frame-template#78]
stuck at `lein garden auto`, `lein figwheel dev` won't go on.

**Comment by gadfly361** [comment]
@yqrashawn can you try running `lein deps` first, and then run `lein dev`

**Comment by gadfly361** [comment]
@yqrashawn I am able to reproduce, thanks!

**Comment by gadfly361** [comment]
@yqrashawn Unfortunately, the `+aliases` has been cumbersome to maintain, and I think it will impede to the addition of new optional profiles.  As a result, I have decided to remove `+aliases` as an option.

Thanks again for opening this issue!
