### ISSUE TITLE
README.md sholud be updated replacing phantomjs to phantomjs-prebuilt

### ISSUE THREAD

**Issue by armikhalev** [Day8/re-frame-template#80]
Currently README.md [Run tests section](https://github.com/Day8/re-frame-template#run-tests-if-using-test) refers to phantomJS library which is by now deprecated.
README.md should be updated to [phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt) as indicated at phantomjs npm page.

**Comment by gadfly361** [comment]
@armikhalev Thanks for opening this issue! I updated the READMEs to suggest using chrome-headless instead of phantomjs or phantomjs-prebuild.
