### ISSUE TITLE
src/leiningen/new/re_frame/src/cljs/routes.cljs: Should use :import for goog.history.EventType instead of :require

### ISSUE THREAD

**Issue by ghost** [day8/re-frame-template#81]
It has been recommended to use `:import` for `goog.history.EventType` instead of `:require`: http://clojurescriptmadeeasy.com/blog/when-do-i-use-require-vs-import.html

See-Also: https://github.com/clj-commons/secretary/issues/98

**Comment by superstructor** [comment]
Fixed by @wegi in #94.
