### ISSUE TITLE
Use figwheel-main instead of lein-figwheel

### ISSUE THREAD

**Issue by PabloReszczynski** [Day8/re-frame-template#83]
Since lein-figwheel has been deprecated for the new [figwheel-main](https://github.com/bhauman/figwheel-main), it would be nice if the re-frame template stayed up to date. I don't know if such a change would be difficult for this project.

**Comment by gadfly361** [comment]
@PabloReszczynski Thanks for bringing this request up! 

I agree that looking in to replacing lein-figwheel with figwheel-main is a good idea :+1: Unfortunately, it would be a bit of a rewrite, and realistically, I don't think I will have time in the next couple of months.

(As an aside, has lein-figwheel been deprecated? I know it isn't the focus anymore, but I don't see anything about deprecation in its README.)

**Comment by danielcompton** [comment]
@gadfly361 AFAIK lein-figwheel hasn't been deprecated, it's just not the main focus.

**Comment by superstructor** [comment]
And/or could consider supporting [shadow-cljs](https://github.com/thheller/shadow-cljs). Possibly could be optional profiles ?

**Comment by superstructor** [comment]
Move to shadow-cljs completed. Closing for now until there is a compelling case made to support optional profiles for multiple build systems.
